config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root to: 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index new create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  # validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  ROLES = %i[admin default].freeze

  # rubocop:disable Style/RedundantSelf
  def is?(requested_role)
    self.role == requested_role.to_s
  end
  # rubocop:enable Style/RedundantSelf

  def recent_posts
    posts.order('created_at Desc').limit(3)
  end

  def count_comments
    comments.count
  end

  def count_likes
    likes.count
  end

  def count_posts
    posts.count
  end

  after_initialize :set_defaults

  def set_defaults
    self.posts_counter ||= 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user2 = User.find params[:id]
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bio.html.erb
<div>
  <p>@user2.name</p>
</div>

app/views/users/_cross.html.erb
<div class="cross-div">
<%= image_tag(@user2.photo, :size => '150x150') if @user2.photo %>
<div class="index-box">
  <p><%=link_to @user2.name, user_path(@user2.id) %></p>
  <p class="post-counter">Number of posts: <%= @user2.count_posts %></p>
</div>
</div>

app/views/users/_user.html.erb
<li id="users-item">

  
  <%= image_tag(user.photo, :size => '150x150') if user.photo %>

  <div class="index-box">
    <p>
      <%=link_to user.name, user_path(user.id) %>
    </p>

    <p class="post-counter">
      Number of posts <%= user.count_posts %>
    </p>
  </div>

</li>

app/views/users/index.html.erb
<ul class="unordered">

  <% @users.each do |user| %>
    <%= render user %>
  <% end %>


</ul>

app/views/users/show.html.erb
<div class="one-post">
  <%= render 'cross' %>
  <div class="bio">
    <h4>Bio</h4>
    <p><%= @user2.bio %></p>
  </div>
  <% @user2.recent_posts.each do |post| %>
    <div class="sev-post">
      <p><%= link_to post.title, user_post_path(@user2, post) %></p>
      <p><%= post.text %></p>
      <div class="post-part">
        <p class="post-comment">Comments: <%= post.count_comments %></p>
        <p class="post-like">Likes: <%= post.count_likes %></p>
      </div>
    </div>

  <% end %>
</div>

<button class="btn"><%= link_to  "See posts", user_posts_path(@user2)  %></button>