config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  root to: 'users#index'

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show destroy] do
      resources :comments, only: %i[new create destroy]
      resources :likes, only: %i[create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index new create]
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: :post_id
  has_many :likes

  # validates :title, presence: true, length: { maximum: 250 }
  # validates :commentscounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :likescounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_user_posts_count
    author.increment!(:postscounter)
  end

  def recent_comments
    comments.order('created_at Desc').limit(5)
  end

  def count_comments
    comments.count
  end

  def count_likes
    likes.count
  end

  after_initialize :set_defaults

  def set_defaults
    self.likescounter ||= 0
    self.commentscounter ||= 0
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApiController
      load_and_authorize_resource
      def index
        p_id = @current_user.id
        @user2 = User.find_by(id: p_id)
        @posts = @user2.posts
        render json: @posts
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  around_action :skip_bullet

  def skip_bullet
    Bullet.enable = false
    yield
  ensure
    Bullet.enable = true
  end

  def index
    @user2 = User.find(params[:user_id])
    @posts = @user2.posts.includes(:comments)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Success'
          redirect_to user_posts_path(current_user, @post)
        else
          flash.now[:error] = 'Error: Post could not be saved'
          render :new, locals: { post: @post }, status: 442
        end
      end
    end
  end

  def show
    @posta = Post.find params[:id]
  end

  def destroy
    @post = Post.find(params[:id])
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.destroy!
    redirect_to user_posts_path(id: @author.id), notice: 'Post was deleted successfully!'
  end

  private

  def post_params
    params.require(:post).permit(:title, :text).merge(author: current_user)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li class="post-item">
  <div class="sev-post">
    <p><%= link_to post.title, user_post_path(@user2, post) %></p>
    <p><%= post.text %> </p>
    <div class="post-part">
      <p>Comments: <%= post.count_comments %> </p>
      <p>Likes: <%= post.count_likes %> </p>
    </div>
  </div>
  <div class="recent-comments">
    <% post.recent_comments.each do |comment| %>
      <p><%= comment.author.name %>:<%= comment.text %>
    <% end %>
  </div>
</li>

app/views/posts/index.html.erb
<%= render "users/cross" %>

<% @posts.each do |post| %>
  <%= render post %>

<% end %>

<%= link_to 'Add new post', new_user_post_path(@user2) %>
<button>Pagination</button>

app/views/posts/new.html.erb
<h1>My Post</h1>

<%= form_with model: @post, url: user_posts_url, method: :post, local: true, scope: :post do |f| %>
  <div>
    <%= f.label :Title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :Text %>
    <%= f.text_area :text, size: '20x5' %>
  </div><br>

  <%= f.submit 'Add Post' %>


<% end %>

app/views/posts/show.html.erb
<div class="owner-post">
  <div class="one-post">
    <h3 class="head-3"> <%= @posta.title %> by <%= @posta.author.name %> </h3>
    <div class="post-part">
      <p class="post-comment">Comments: <%= @posta.count_comments %>
      <p class="post-like">Likes: <%= @posta.count_likes %>
      
    </div>
    <div>
      <p class="diff"><%= @posta.text %> </p>
    </div>
    
  </div>
  <div class="recent-comments">
    <% @posta.recent_comments.each do |comment| %>
      <p><%= comment.author.name %>:<%= comment.text %> </p>
      <% if can? :destroy, Comment %>
        <%= button_to 'Delete', user_post_comment_path(author_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete %>
      <% end %>
    <% end %>
  </div>
</div>
<% if can? :destroy, Post %>
  <%= button_to 'Delete', user_post_path(author_id: @posta.author.id, post_id: @posta.id), method: :delete %>
<% end %>
<%= link_to 'new', new_user_post_comment_path(@posta.author, @posta) %>
<%= render partial: 'likes/form' %>